 name: Hello World Workflow

  on:
     push:
       branches:
         - fur1

   jobs:
     say-hello:
       runs-on: ubuntu-latest

       steps:
       - name: Print Hello World!
         run: echo "Hello World!"
